[build]
  command = "npm run build"
  publish = "dist"

[environment]
  NODE_ENV="development"

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

[[headers]]
  for = "/images/*"
  [headers.values]
    cache-control = "public,max-age=2592000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    cache-control = "public,max-age=2592000"

[[headers]]
  for = "/*"
  [headers.values]
    X-Version = "VERSION"
